/**
 * The chat card a `renderUI` tool call becomes.
 *
 * Three states, and the transitions between them are one-way:
 *
 * - **composing** — the arguments are still streaming. A skeleton read off the partial JSX, so the
 *   wait shows the shape of the answer rather than a spinner.
 * - **live** — the newest interface in the chat. Controls are writable; one button submits.
 * - **frozen** — submitted, or simply left behind by the conversation. Read-only, and visibly so.
 *
 * Chrome is deliberately absent: no title bar, no "generated by" banner, no card-within-a-card.
 * The transcript is already full of hand-built cards at this width and border radius, and an
 * ephemeral interface earns its place by looking like one of them, not by announcing itself.
 */

import { useMemo } from "react";
import { Check, WarningCircle } from "@phosphor-icons/react";
import {
  GENERATIVE_UI_CATALOG_VERSION,
  type GenerativeUiResult,
} from "@gadgets/workshop-shared/api";
import styles from "../ChatInterface.module.css";
import type { GenerativeUiClient } from "./client";
import type { CatalogContext } from "./catalog";
import { RenderNode } from "./TreeRenderer";
import { useGenerativeUiCardState } from "./state";
import { MAX_SKELETON_DEPTH, sketchPartialJsx, type SkeletonItem } from "./jsxSkeleton";

/** The card shell every state shares, so they occupy the same shape in the transcript. */
function CardShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-w-0 max-w-[640px] text-[14px] leading-5 tracking-[-0.25px] text-kumo-subtle">
      <div className="overflow-hidden rounded-2xl border border-kumo-line bg-kumo-base px-4 py-3.5">
        {children}
      </div>
    </div>
  );
}

/** The status line under a frozen card. Mirrors the transcript's own 11px footer rows. */
function CardFooter({
  tone,
  icon,
  children,
}: {
  tone: "neutral" | "success" | "danger";
  icon?: React.ReactNode;
  children: React.ReactNode;
}) {
  const toneClass = tone === "success"
    ? "text-kumo-success"
    : tone === "danger"
      ? "text-kumo-danger"
      : "text-kumo-inactive";
  return (
    <div className={`mt-3 flex items-center gap-1.5 border-t border-kumo-line/60 pt-2 text-[11px] leading-4 ${toneClass}`}>
      {icon}
      <span>{children}</span>
    </div>
  );
}

// ── Composing ───────────────────────────────────────────────────────────────────────────────────

/**
 * Skeleton geometry per catalog component, so the preview reads as the thing being written.
 *
 * Layout components draw nothing: `Stack` and `Row` are containers, and a bar for one would claim
 * content the model hasn't written yet. They still count, through the indentation of what's inside.
 */
const SKELETON_SHAPES: Record<string, string[]> = {
  Stack: [],
  Row: [],
  Heading: ["h-3 w-[38%]"],
  Text: ["h-2.5 w-full", "h-2.5 w-[62%]"],
  Badge: ["h-4 w-16 rounded-full"],
  Divider: ["h-px w-full"],
  Button: ["h-8 w-28 rounded-lg"],
  Input: ["h-2 w-20", "h-8 w-full rounded-lg"],
  Select: ["h-2 w-20", "h-8 w-full rounded-lg"],
  Checkbox: ["h-3.5 w-[55%]"],
  Slider: ["h-2 w-20", "h-1.5 w-full rounded-full"],
  Table: ["h-6 w-full rounded-t-lg", "h-5 w-full", "h-5 w-full"],
  ProgressBar: ["h-2 w-24", "h-1.5 w-full rounded-full"],
  Callout: ["h-9 w-full rounded-xl"],
  KeyValue: ["h-2.5 w-[70%]", "h-2.5 w-[55%]"],
  Card: ["h-2.5 w-[45%]"],
};

/** What a component the skeleton has no shape for looks like: one modest line. */
const DEFAULT_SHAPE = ["h-2.5 w-[48%]"];

const INDENTS = ["", "pl-3", "pl-6", "pl-9"] as const;

function SkeletonRow({ item }: { item: SkeletonItem }) {
  const bars = SKELETON_SHAPES[item.type] ?? DEFAULT_SHAPE;
  return (
    <div className={`flex flex-col gap-1.5 ${INDENTS[Math.min(item.depth, MAX_SKELETON_DEPTH)]}`}>
      {bars.map((bar, index) => (
        <div key={index} className={`rounded-[3px] bg-kumo-fill ${bar}`} />
      ))}
    </div>
  );
}

/**
 * The card while the tool's arguments are still arriving.
 *
 * `jsx` is whatever of the input has streamed so far, or empty if this deployment's backend
 * doesn't stream `renderUI` arguments -- in which case the card is just the shimmering label,
 * which is exactly what the rest of the transcript shows for a tool it can't preview.
 */
export function ComposingUiCard({ jsx = "" }: { jsx?: string }) {
  const rows = useMemo(
    () => sketchPartialJsx(jsx).filter((item) => (SKELETON_SHAPES[item.type] ?? DEFAULT_SHAPE).length > 0),
    [jsx],
  );
  return (
    <CardShell>
      <div
        className={`text-[13px] leading-[18px] ${styles.thinkingShimmer}`}
        // The skeleton is decoration; the label is what a screen reader should hear, once.
        role="status"
      >
        Composing interface…
      </div>
      {rows.length > 0 && (
        <div className="mt-3 flex flex-col gap-2.5 motion-safe:animate-pulse" aria-hidden="true">
          {rows.map((item, index) => <SkeletonRow key={index} item={item} />)}
        </div>
      )}
    </CardShell>
  );
}

// ── Unreadable ──────────────────────────────────────────────────────────────────────────────────

/**
 * A recorded interface whose tree can't be read.
 *
 * Only reachable for a tree persisted by a validator this build disagrees with; a `renderUI` that
 * *failed* never got this far and shows the transcript's ordinary error row instead.
 */
export function UnreadableUiCard() {
  return (
    <CardShell>
      <div className="flex items-center gap-2 text-[13px] leading-[18px] text-kumo-inactive">
        <WarningCircle size={14} className="flex-shrink-0" />
        <span>This interface can&rsquo;t be displayed by this version of the app.</span>
      </div>
    </CardShell>
  );
}

// ── Rendered ────────────────────────────────────────────────────────────────────────────────────

export function GenerativeUiCard({
  toolCallId,
  result,
  client,
  interactive,
}: {
  toolCallId: string;
  result: GenerativeUiResult;
  /**
   * Null for a card with no live backend (a historical card, or the QA harness). The card renders
   * identically; it simply never calls out.
   */
  client: GenerativeUiClient | null;
  interactive: boolean;
}) {
  const { state, status, frozen, setBound, submit } = useGenerativeUiCardState({
    toolCallId,
    stateDefaults: result.stateDefaults,
    client,
    interactive: interactive && client !== null,
  });

  const ctx: CatalogContext = useMemo(() => ({
    frozen,
    setBound,
    submit,
    pendingAction: status.kind === "submitting" ? status.action : null,
  }), [frozen, setBound, submit, status]);

  const submitted = status.kind === "submitted" || status.kind === "submitting";

  // At most one footer, so a card that is both historical and from a newer catalog doesn't grow a
  // stack of disclaimers taller than the interface itself.
  const note = result.catalogVersion > GENERATIVE_UI_CATALOG_VERSION
    ? "built for a newer version of the app"
    : null;
  const footer = status.kind === "failed"
    ? { tone: "danger" as const, icon: <WarningCircle size={12} className="flex-shrink-0" />,
        text: `Couldn't send: ${status.error}` }
    : submitted
      ? { tone: "success" as const, icon: <Check size={12} weight="bold" className="flex-shrink-0" />,
          text: "Submitted" }
      // A card the conversation has moved past says so once, quietly, rather than leaving the user
      // to discover it by clicking a dead button.
      : !interactive
        ? { tone: "neutral" as const, icon: undefined, text: "No longer active" }
        : null;

  const footerText = footer
    ? note ? `${footer.text} · ${note}` : footer.text
    : note ? "Built for a newer version of the app" : null;

  return (
    <CardShell>
      <div
        className={`flex min-w-0 flex-col gap-2.5 transition-opacity duration-300 ease-out ${
          frozen ? "opacity-75" : ""
        }`}
      >
        <RenderNode node={result.tree} state={state} ctx={ctx} />
      </div>

      {footerText !== null && (
        <CardFooter tone={footer?.tone ?? "neutral"} icon={footer?.icon}>
          {footerText}
        </CardFooter>
      )}
    </CardShell>
  );
}
